id: PCB3A5688
initial_creation_type: input
source_metadata:
  title: Middle Way Series
  language: fr
  description: 'The following texts are available as part of our series on the Middle
    Way (Madhyamaka/Mādhyamika; dbu ma) philosophy:'
  volume:
    6569df30ff8844e188125bf7e8043427:
      title: Conveying the Essence of the Middle Way of Consequence
      parent: General
    23600859573543c7b49148e440c75f15:
      title: 'The Words of Candra: The Definitive Secret of the Great Middle Way of
        Consequence Beyond Extremes, the Fundamental Intent of All the Tathāgatas'
      parent: General
    a5092af6105943639ced873f7f9ad3cc:
      title: 'The Seed of Reasoning: Notes on the Five Great Logical Arguments of
        the Middle Way'
      parent: General
    00c51e9bd0c9420ab0f562d9ea34ba76:
      title: A Step-by-Step Meditation on the Definitive Meaning of the Great Middle
        Way
      parent: General
    175c884bb6694eecb54c08b924b1085c:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: General
    4138b8a44a9a423cb2a5717e8bb7bcb0:
      title: Profound Instruction on the View of the Middle Way
      parent: General
    bef012cc9a23416f81a834ad632f62bb:
      title: 'Clarifying the Essence: A Summary of the Instructions on the View of
        the Middle Way'
      parent: General
    9e6fc7199648414c82e87b0596328e03:
      title: Commentary on the Madhyamakāvatāra—Part 1—Collection of Reasoning
      parent: Madhyamakāvatāra
    7cab6621943d472081bb4f3a320197f5:
      title: Commentary on the Madhyamakāvatāra—Part 2—Title and Translators Homage
      parent: Madhyamakāvatāra
    9e1321c4ace74521b4bc21a1be1534b4:
      title: Prologue to Introduction to the Middle Way (Madhyamakāvatāra)
      parent: Madhyamakāvatāra
    206b7084d6a34639afbe38f3366eb6c6:
      title: Concise Middle Way Aspiration
      parent: Prayers
    ab7feda80b7c477c9383c2a280beb040:
      title: Middle Way Aspiration
      parent: Prayers
created_at: '2022-03-01T04:42:52.488149'
last_modified_at: '2022-03-01T04:42:52.488152'
